### ISSUE TITLE
Clicking button to present popover gets "Attempt to present" error and the popover doesn't appear

### ISSUE THREAD

**Issue by wisepmlin** [aheze/Popovers#14]
Attempt to present <_TtGC7SwiftUI29PresentationHostingControllerVS_7AnyView_: 0x124db27e0> on <_TtGC7SwiftUI19UIHostingControllerGVS_15ModifiedContentVS_7AnyViewVS_12RootModifier__: 0x107013f20> (from <_TtGC7SwiftUI41StyleContextSplitViewNavigationControllerVS_14NoStyleContext_: 0x10683d600>) which is already presenting <sniffer_knife.PopoverContainerViewController: 0x116008170>.
The result of the above error：
When clicking on this error, the system can correctly feedback the Boolean value, but the view does not pop up and appear on the screen

**Comment by aheze** [comment]
I have the same issue here: https://github.com/aheze/Popovers/issues/11. I'm working on a fix.

**Comment by wisepmlin** [comment]
Wait for the repair

**Comment by aheze** [comment]
@wisepmlin fixed in [1.2.0](https://github.com/aheze/Popovers/releases/tag/1.2.0)! Leave a comment if it still doesn't work.
