### ISSUE TITLE
Interaction exception！The root cause of the problem was not found？

### ISSUE THREAD

**Issue by wisepmlin** [aheze/Popovers#17]
What bothers me is that! Popovers packages in use and the system's navigationgview column in the first column of the folded page button and sheet and several views of the reaction will work will conflict, often making popovers work abnormally!
Problem Description:
1, the user enters the rendered popovers UI pop-up window, click the folding page button, the second popovers will not work, continue to test to open the sheet window, multiple clicks are invalid, wait for several clicks, everything works normally # #

**Comment by aheze** [comment]
@wisepmlin can you attach an image of the problem? Also it would be helpful if you made a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_working_example#:~:text=In%20computing%2C%20a%20minimal%20working,to%20be%20demonstrated%20and%20reproduced.&text=A%20minimal%20working%20example%20may,short%20self%2Dcontained%20correct%20example.)

**Comment by wisepmlin** [comment]
//
//  ContentView.swift
//  sniffer_knife
//
//  Created by wise on 2021/4/9.
//

import SwiftUI
import Introspect
import CoreData
import SwiftUIX

struct ContentView: View {
    @Environment(\.colorScheme) private var colorScheme: ColorScheme
    @EnvironmentObject var appSettings: AppSettings
    @State private var showPrimary: Bool = false
    @State private var presentingUUID = UUID()
    @State private var notificationOfDwellTime: Double = 3
    init(){
        UITableView.appearance().backgroundColor = .clear
        UITableViewCell.appearance().backgroundColor = .clear
        UITableView.appearance().tableFooterView = UIView()
    }
    
    var body: some View
    {
        NavigationView
        {
            SK_TableBar()
                .frame(maxWidth: 420)
                .popover(
                    present: $appSettings.appNotice,
                    attributes: {
                        $0.sourceFrameInset = UIEdgeInsets(-CGFloat.bl_4.custom(num: 5))
                        $0.position = .relative(
                            popoverAnchors: [.top]
                        )
                        $0.presentation.transition = .move(edge: .top)
                        $0.dismissal.transition = .move(edge: .top)
                        $0.dismissal.mode = [.dragUp]
                        $0.dismissal.dragDismissalProximity = 0.1
                    }
                ) {
                    NotificationViewPopover(msgBody: $appSettings.appMsgBody)
                        .onAppear {
                            presentingUUID = UUID()
                            let currentID = presentingUUID
                            DispatchQueue.main.asyncAfter(deadline: .now() + notificationOfDwellTime) {
                                if currentID == presentingUUID {
                                    appSettings.appNotice = false
                                }
                            }
                        }
                        .onDisappear(perform: {
                            //确保弹窗信息被关闭
                            appSettings.appNotice = false
                        })
                }
            SecondView()
            ThirdView()
        }
        .environmentObject(self.appSettings)
        .overlay(ZStack{
            if !appSettings.userIsFirstLaunch {
                AddUserInfo()
                    .transition(.move(edge: .bottom))
            }
        })
        .accentColor(Color.navigationBarItemsColor)
        .introspectNavigationController{ nav in
            DispatchQueue.main.async {
                nav.splitViewController?.minimumPrimaryColumnWidth = 420
                nav.splitViewController?.maximumPrimaryColumnWidth = 420
                nav.splitViewController?.minimumSupplementaryColumnWidth = 240
                nav.splitViewController?.maximumSupplementaryColumnWidth = 240
                nav.splitViewController?.show(.primary)
            }
        }
        .transition(.combineMoveTopAndScale)
        .onAppear(perform: {
            AppFirestAction()
            //载入上次选择的产品
            appSettings.selectedProductId = appSettings.onboardingProductId
        })
    }
    
    @MainActor
    private func AppFirestAction()
    {
        //当前版本第一次启动
        if UserDefaults.isFirstLaunchOfNewVersion() {
            
        }
        //应用第一次启动
        if UserDefaults.isFirstLaunch() {
            
        }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
            .previewDevice("iPad Pro (11-inch) (3rd generation)")
            .preferredColorScheme(.dark)
    }
}

struct SecondView: View {
    var body: some View {
        ZStack {
            Color.s_c.edgesIgnoringSafeArea(.all)
        }
    }
}

struct ThirdView: View {
    var body: some View {
        ZStack {
            Color.s_c.edgesIgnoringSafeArea(.all)
        }
    }
}

The above code, single modified "nav.splitViewController?. show(.primary)" when popover's proactive can work normally, but when the user manually primary, first click the interactive button corresponding to popover, and then click primary (navigationview first column "left accordion button"), even if popover's present print as true does not work properly. Other pop-up types that add popover to multiple node files at the same time are not working at this time.

**Comment by wisepmlin** [comment]
![画板](https://user-images.githubusercontent.com/74945717/152632668-b2ad361d-9504-4f68-a852-453a9ef77ef7.png)

**Comment by wisepmlin** [comment]
At the same time, it was found that adding pop-up boxes can make .sheets, .fullScreenCover appear and disappear animations unavailable.

**Comment by aheze** [comment]
@wisepmlin that is a known issue, am almost done with the fix.

**Comment by wisepmlin** [comment]
You are amazing! I would like to ask when to update the repaired version.
Our team is also experimenting with the swiftUI framework and the current contact is also in infancy! More in the application layer!

**Comment by aheze** [comment]
Just created a new GitHub issue: #21. I'll release the fix tomorrow along with some other new features :D

**Comment by wisepmlin** [comment]
That's great!

**Comment by aheze** [comment]
@wisepmlin [1.3.0](https://github.com/aheze/Popovers/releases/tag/1.3.0) is released. Can you check if this problem still occurs after updating?

**Comment by aheze** [comment]
Closing for now - feel free to reopen if the issue still isn't resolved
