### ISSUE TITLE
Values bound by UserDefaults are not accepted, resulting in popover not working

### ISSUE THREAD

**Issue by wisepmlin** [aheze/Popovers#19]
```swift
@Published var userIsFirstLaunch: Bool {
    didSet {
        UserDefaults.standard.set(userIsFirstLaunch, forKey: "userIsFirstLaunch")
    }
}
```
```swift
.popover(
    present: $appSettings.appNotice,
    attributes: {
        $0.sourceFrameInset = UIEdgeInsets(16)
        $0.position = .relative(
            popoverAnchors: [
                .top,
            ]
        )
        $0.presentation.transition = .move(edge: .top)
        $0.dismissal.transition = .move(edge: .top)
        $0.dismissal.mode = [.dragUp]
        $0.dismissal.dragDismissalProximity = 0.1
    }
) {
    NotificationViewPopover(msgBody: $appSettings.appMsgBody)
        .onAppear {
            presentingUUID = UUID()
            let currentID = presentingUUID
            DispatchQueue.main.asyncAfter(deadline: .now() + notificationOfDwellTime) {
                if currentID == presentingUUID {
                    appSettings.appNotice = false
                }
            }
        }
}
```

**Comment by aheze** [comment]
@wisepmlin can you show the code where you use `userIsFirstLaunch`? I only see the declaration, not where it's referenced or how it's related to the popover

**Comment by wisepmlin** [comment]
import SwiftUI

struct SK_TableBar: View
{
    @Environment(\.managedObjectContext) var managedObjectContext
    @EnvironmentObject var appSettings: AppSettings
    @FetchRequest(entity: User.entity(), sortDescriptors: [NSSortDescriptor(keyPath: \User.updatedAt, ascending: true)], animation: Animation.golden_ratio_animation_two) var users: FetchedResults<User>
    @State private var presentingUUID = UUID()
    @State private var notificationOfDwellTime: Double = 2
    let tabs = BarData().bardatas
    
    var product: some View {
        VStack(spacing: CGFloat.zero) {
            ForEach(users) { user in
                ProdctsList(user: user,
                            pageTitle: tabs[appSettings.selectedTab].text)
                    .environmentObject(self.appSettings)
                    .environment(\.managedObjectContext, self.managedObjectContext)
            }
        }
    }
    
    var body: some View {
        if #available(iOS 15.0, *) {
            let _ = Self._printChanges()
        }
        ZStack {
            switch appSettings.selectedTab {
            case 0:
                product
            case 1:
                ComponentBar()
            case 2:
                LearnBar()
            case 3:
                AccomplishmentBar()
            default:
                EmptyView()
            }
        }
        .background(Color.s_c.edgesIgnoringSafeArea(.all).scaleEffect(2))
        .toolbar{
            ToolbarItem(placement: .bottomBar){
                HStack {
                    LazyVGrid(columns: Array(repeating: GridItem(spacing: 0), count: 4)) {
                        ForEach(tabs) { index in
                            Button(action: {
                                appSettings.selectedTab = index.id
                            }, label: {
                                #if targetEnvironment(macCatalyst)
                                macToolbarBottomBar(id: index.id, image: index.image, selectedImage: index.selectedImage, text: index.text)
                                #else
                                iosToolbarBottomBar(id: index.id, image: index.image, selectedImage: index.selectedImage, text: index.text)
                                #endif
                            })
                                .buttonStyle(PrintReportBtnStyle(scale: 0.9, radiusFuzzy: 0))
                        }
                    }
                }
            }
        }
        .debugPrint("发起了通知弹窗要求为：\(appSettings.appNotice)")
        .popover(
            present: $appSettings.appNotice,
            attributes: {
                $0.sourceFrameInset = UIEdgeInsets(16)
                $0.position = .relative(
                    popoverAnchors: [.top]
                )
                $0.presentation.transition = .move(edge: .top)
                $0.dismissal.transition = .move(edge: .top)
                $0.dismissal.mode = [.dragUp]
                $0.dismissal.dragDismissalProximity = 0.1
            }
        ) {
            NotificationViewPopover(msgBody: $appSettings.appMsgBody)
                .onAppear {
                    presentingUUID = UUID()
                    let currentID = presentingUUID
                    DispatchQueue.main.asyncAfter(deadline: .now() + notificationOfDwellTime) {
                        if currentID == presentingUUID {
                            appSettings.appNotice = false
                        }
                    }
                }
        }
    }
    private func macToolbarBottomBar(id: Int, image: String, selectedImage: String, text: String) -> some View {
        HStack(spacing: CGFloat.bl_4){
            Image(systemName: appSettings.selectedTab == id ? image : selectedImage)
                .modifier(SK_Customization(textColor: appSettings.selectedTab == id ? Color.brandeColor : Color.t_t_c, weight: .regular, fontSizeNum: 12))
            Text("\(text)")
                .modifier(SK_14(textColor: appSettings.selectedTab == id ? Color.brandeColor : Color.t_t_c, weight:  appSettings.selectedTab == id ? .bold : .regular))
        }
        .padding(.horizontal, CGFloat.bl_4.fourfold)
        .contentShape(Rectangle())
    }
    
    private func iosToolbarBottomBar(id: Int, image: String, selectedImage: String, text: String) -> some View {
        VStack(spacing: CGFloat.bl_4){
            Image(systemName: appSettings.selectedTab == id ? image : selectedImage)
                .modifier(SK_Customization(textColor: appSettings.selectedTab == id ? Color.brandeColor : Color.t_t_c, weight: .regular, fontSizeNum: 16))
                .padding(.top, CGFloat.bl_4.double)
            Text("\(text)")
                .modifier(SK_10(textColor: appSettings.selectedTab == id ? Color.brandeColor : Color.t_t_c, weight:  appSettings.selectedTab == id ? .bold : .regular))
        }
        .animation(Animation.golden_ratio_animation_two, value: appSettings.selectedTab == id)
        .padding(.horizontal, CGFloat.bl_4.fourfold)
        .contentShape(Rectangle())
    }
}

**Comment by wisepmlin** [comment]
@Published var appNotice: Bool {
        didSet {
            UserDefaults.standard.set(appNotice, forKey: "appNotice")
        }
    }

**Comment by wisepmlin** [comment]
发起了通知弹窗要求为：true
SK_TableBar: @self, @identity, _managedObjectContext, _appSettings, _users, @48, @72, _presentingUUID, _notificationOfDwellTime changed.
发起了通知弹窗要求为：true
SK_TableBar: @self changed.
发起了通知弹窗要求为：true
SK_TableBar: _appSettings changed.
true
进入了产品列表，并读取了产品数据到模型结构
2022-01-30 15:16:59.242293+0800 秀刀[56228:4785191] Metal API Validation Enabled
发起了通知弹窗要求为：true
SK_TableBar: @self changed.
发起了通知弹窗要求为：true
SK_TableBar: _appSettings changed.

**Comment by wisepmlin** [comment]
SK_TableBar: _appSettings changed.

**Comment by wisepmlin** [comment]
Found the issue on my code, resolved
