### ISSUE TITLE
regular sheet animation disappeared when I add the Popover package via Swift Package Manager

### ISSUE THREAD

**Issue by tm00-git** [aheze/Popovers#25]
regular sheets (i.e. .sheet(isPresented: <Binding<Bool>>, onDismiss: <(() -> Void)?(() -> Void)?() -> Void>, content: <() -> View>) ) I use across the app appearance stopped animating. Animation is restored when popover package is removed.

**Comment by aheze** [comment]
@tm00-git what version of Popovers are you using? Popovers v1.2 had some known issues with system animations interference - Popovers v1.3 should fix them.

**Comment by tm00-git** [comment]
@aheze thank you for prompt reply. I indeed installed latest package 1.3.0 and tested multiple times. It appears regular sheet loses animation if it is attached to NavigationView. Attaching two gifs to demonstrate behaviour.
![Without Popovers](https://user-images.githubusercontent.com/81569028/155501408-cb19622e-81c3-4c51-aa95-013b2cbe9cd8.gif)
![With Popovers 1 3 0](https://user-images.githubusercontent.com/81569028/155501425-73bccab9-794c-42db-a71b-2f369c99188b.gif)

**Comment by aheze** [comment]
Weird. For now try attaching the `.popover` modifier somewhere other than the sheet — if you use a `.relative` position, where it's attached doesn't matter.

**Comment by tm00-git** [comment]
the strange thing is that animations on regular sheet stops working as soon thePopovers package (v 1.3.0) is added through Xcode package manager, even without attaching .popover. Could be related with modifiers which overwrites system defaults.

**Comment by Nickersoft** [comment]
Would just like to hop in here and say that I'm experiencing the same 👋🏼

**Comment by aheze** [comment]
Hmm ok. I’m super busy this week but will check it out as soon as I can

**Comment by aheze** [comment]
@tm00-git @Nickersoft fixed in https://github.com/aheze/Popovers/releases/tag/1.3.2.
