### ISSUE TITLE
No Arrow

### ISSUE THREAD

**Issue by tazmancoder** [aheze/Popovers#28]
I really like the library. However, in the documentation in the ShowRoom you show a standard popover that has the arrow pointing down to something. I can't seem to figure out why an arrow is not showing on my popover, here is the code I'm using. Not sure if I'm missing something.

```swift
.popover(
    present: $promptAddContact,
    attributes: {
        $0.position = .absolute(
            originAnchor: .bottom,
            popoverAnchor: .topLeft
        )
        $0.presentation.animation = .spring()
        $0.presentation.transition = .move(edge: .top)
        $0.dismissal.animation = .spring(response: 2, dampingFraction: 0.8, blendDuration: 3)
        $0.dismissal.transition = .move(edge: .top)
    }
) {
    Text("Click here to add contacts")
        .smallPadding()
        .foregroundColor(.white)
        .background(.blue)
        .cornerRadius(10)
        .onAppear {
            DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                promptAddContact = false
            }
        }
}
```

**Comment by aheze** [comment]
Hey! By default Popovers shows the view you pass in — `Text("Click here to add contacts")` — and nothing else. The arrow is another custom view inside the `Templates` folder called `Container`. Here's how you use it:

```swift
.popover(
    present: $present,
    attributes: {
        $0.sourceFrameInset.top = -8
        $0.position = .absolute(
            originAnchor: .top,
            popoverAnchor: .bottom
        )
    }
) {
    Templates.Container { /// here!
        Text("This is a pretty standard-looking popover with an arrow.")
    }
    .frame(maxWidth: 300)
}
```

Result:

<img width="282" alt="Screen Shot 2022-04-10 at 9 48 31 AM" src="https://user-images.githubusercontent.com/49819455/162630382-ad260052-3a02-4eb9-b8e8-072f9dbcf6b7.png">


The `Container` view also has some additional optional parameters that you can configure:
```swift
Templates.Container(
    arrowSide: .bottom(.mostClockwise),
    backgroundColor: .green
) {
    Text("This is a pretty standard-looking popover with an arrow.")
        .foregroundColor(.white)
}
.frame(maxWidth: 300)
```

Result:

<img width="293" alt="Screen Shot 2022-04-10 at 9 51 10 AM" src="https://user-images.githubusercontent.com/49819455/162630490-b143a5e8-fe43-4c27-bb3b-9ad73cb75c93.png">

You can find more example usage inside the [sample app](https://github.com/aheze/Popovers/raw/main/Examples/PopoversXcodeApp.zip).

**Comment by tazmancoder** [comment]
Thanks,

Sorry I have one last question. How can I make the pop up come up when the view loads. I’ve tried onAppear and it doesn’t seem to work.

Thanks

-Mark/*

Mark Perryman
Apple (MAC) Enthusiast
(435) 882-1008

**Comment by aheze** [comment]
Closing for now. @tazmancoder, responding to your question in https://github.com/aheze/Popovers/issues/30
