### ISSUE TITLE
How can I add  dynamic content view in Popover ?

### ISSUE THREAD

**Issue by calvingit** [aheze/Popovers#29]
Is it only a static menu popover? If I want to change the menu title every time, what should I do? I don't want to cache the selected index.

**Comment by aheze** [comment]
See [State Re-Rendering](https://github.com/aheze/Popovers#state-re-rendering) — Popovers can be dynamic, you just need to pass down a `Binding`.

**Comment by calvingit** [comment]
Sorry, I use popovers in UIKit with `Templates`.

**Comment by aheze** [comment]
You will need to use a `ObservableObject` view model — it allows the popover to update. Something like this:

```swift
class ViewModel: ObservableObject {
    @Published var text = "Hello"
}

struct ContentView: View {
    @ObservableObject var model: ViewModel
    var body: some View {
        Text(model.text)
    }
}
```

```swift
let model = ViewModel()
let popover = Popover { ContentView(model: model) }
present(popover)

DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
	model.text = "Changed!"
}
```
