### ISSUE TITLE
No window was found when presenting popover.

### ISSUE THREAD

**Issue by BaileyM** [aheze/Popovers#32]
I received the above message in the log when I attempted to present a popover. My app uses WindowGroup when setting up the root view.

Here is my popover code:

'''
.popover(present: $presentTip) {
	Text("Testing")
} 
'''

**Comment by BaileyM** [comment]
Switching from version 1.0.0 to 1.3.0 fixed this for me.

**Comment by aheze** [comment]
Good to know, thanks! If you still get the issue just leave another comment.
