### ISSUE TITLE
Opening downloaded Xcode example project causes Xcode to hang

### ISSUE THREAD

**Issue by stbdang** [aheze/Popovers#37]
I've downloaded the example project in the readme (https://github.com/aheze/Popovers/raw/main/Examples/PopoversXcodeApp.zip) and opened it from where it was downloaded (~/Downloads), and it caused Xcode to hang for a long time. 

It opened eventually, and I noticed that it loaded all my folders and files in ~/, which explains why it took so long. If I clone this repo and open the example project, it opens fine without any issue.

I think there might be some hard-coded relative paths in the example Xcode project? 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/4217719/170899778-97af6de6-a992-401d-a838-ca4d54b439b6.png">

**Comment by aheze** [comment]
Weird, I'll take a look. Thanks for letting me know!

**Comment by ConfusedVorlon** [comment]
I get the same issue. 
When I first launched the project, it caused XCode to ask for permission to access my calendar and reminders. I denied that permission.
Is this related?

**Comment by aheze** [comment]
Wow, that's seriously weird. Investigating...

![Screen Shot 2022-08-09 at 9 42 28 PM](https://user-images.githubusercontent.com/49819455/183817519-0ef6adc8-7714-4687-94f8-c9ce72ae6486.png) | ![Screen Shot 2022-08-09 at 9 42 31 PM](https://user-images.githubusercontent.com/49819455/183817524-1341e128-326c-4ae3-8fee-902e769cf9d5.png) | ![Screen Shot 2022-08-09 at 9 42 33 PM](https://user-images.githubusercontent.com/49819455/183817531-f2cc144b-ae88-483d-b528-76e3263820dd.png) | ![Screen Shot 2022-08-09 at 9 42 35 PM](https://user-images.githubusercontent.com/49819455/183817538-3f030a36-088e-4b88-a3fd-b2e76d2c41d5.png)
--- | --- | --- | ---
