### ISSUE TITLE
Custom Layout iOS16

### ISSUE THREAD

**Issue by Yurssoft** [aheze/Popovers#46]
Have you seen this brand new API?
I have built similar and much simplier popovers on this API. If you are interested, I'd be happy to talk and possibly somehow contribute if it is makes sense.
In any case, here is session.

https://developer.apple.com/videos/play/wwdc2022/10056/

P.S. Library is fantastic! Comments are awesome😎

**Comment by aheze** [comment]
Hey! Yeah, I've saw the new Layout API but I haven't got into it yet. Definitely something I'll be looking into soon.

Thanks, if you have any ideas with Layouts I'd down to chat. Feel free to open a PR too!

**Comment by Yurssoft** [comment]
Sure! Will try to come up with something. While I think, I close this, as count of open issues always matters🙃
