### ISSUE TITLE
How to choose the standard UI design?

### ISSUE THREAD

**Issue by NickG-DK** [aheze/Popovers#49]
Great work you have been doing, but I was wondering how I could choose the standard UI design, that is being showcased in the showroom.

**Comment by aheze** [comment]
Thanks! Just use `Templates.Container`.

```swift
.popover(
    present: $present,
    attributes: {
        $0.sourceFrameInset.top = -8
        $0.position = .absolute(
            originAnchor: .top,
            popoverAnchor: .bottom
        )
    }
) {
    Templates.Container(
        arrowSide: .bottom(.mostClockwise),
        backgroundColor: .green
    ) {
        Text("This is a pretty standard-looking popover with an arrow.")
            .foregroundColor(.white)
    }
    .frame(maxWidth: 300)
}
```

All the showroom examples and various other templates can be found in the example app: https://github.com/aheze/Popovers/raw/main/Examples/PopoversXcodeApp.zip
