### ISSUE TITLE
Different margins on different iOS

### ISSUE THREAD

**Issue by alinless** [aheze/Popovers#53]
Hi!
Firstly, thanks for such nice and shiny library! It is really beautiful
I want to present popover as full screen view with enjoyable animation. I have used the code below. 
If I use the code on 16 it creates additional spaces at the top and bottom (safe areas)
safeAreaInsets were gotten from firstKeyWindow

```
 attributes: {
    $0.position = .relative(popoverAnchors: [.center])
    $0.screenEdgePadding = .init(
       top: safeAreaInsets.top,
       left: safeAreaInsets.leading,
       bottom: safeAreaInsets.bottom,
       right: safeAreaInsets.trailing
    )
    $0.sourceFrameInset = .zero
    
    $0.dismissal.dragMovesPopoverOffScreen = false
    $0.rubberBandingMode = .none
    $0.blocksBackgroundTouches = true
    $0.accessibility.shiftFocus = false
    $0.accessibility.dismissButtonLabel = nil
 }
```
ios15
<img src="https://user-images.githubusercontent.com/94690815/189934135-229c12c2-b347-456c-b37e-a715ebcf0f12.png" width="150">
ios16
<img src="https://user-images.githubusercontent.com/94690815/189934155-f2cf7fe9-8ef3-43cb-b8b9-32b94c8e781e.png" width="150">

The second test was the same, but with $0.screenEdgePadding = .zero
It looks almost fine, but there is a small little red gap at the top of it
ios15
<img src="https://user-images.githubusercontent.com/94690815/189938903-b521bcbb-fe9e-45fe-8d9a-d66064e1b8a6.png" width="150">
ios16
<img src="https://user-images.githubusercontent.com/94690815/189938912-ef73df01-b5ee-47c0-b4de-536b88abb3a3.png" width="150">

It seems like a bug.
And I still have a question, is here a possibility to create a full screen popover?

Thanks for answers

**Comment by aehlke** [comment]
did you resolve?

**Comment by alinless** [comment]
It is an iOS bug. It works fine from iOS 16.4 and upper
