### ISSUE TITLE
Full-width popover

### ISSUE THREAD

**Issue by DavidSReich** [aheze/Popovers#60]
How do I get a popover to be the full width of the screen?
If I make my View full-width it is rendered shifted to the left.

I can modify the BackgroundView in your example like this:
```
        .popover(present: $present) {
            VStack(alignment: .leading) {
                Text("You can put anything you want in the background.")

                HStack {
                    ExampleImage("circle", color: 0x5DCB72)
                    Text("This popover has a `Color.green` background.")
                }
            }
            .frame(width: UIScreen.main.bounds.width) // <<<<< added this line
            .padding()
            .background(.background)
            .cornerRadius(12)
            .shadow(radius: 1)
        } background: {
            Color.green.opacity(0.4)
        }
```

How can I horizontally center it and make it full width?
It looks like this:
![image](https://user-images.githubusercontent.com/12060061/201273836-b9cd44de-2004-4a0a-9011-d3b3c3cd446f.png)

**Comment by DavidSReich** [comment]
Solved!!!!

The layout code gets confused when the width of the View that we are popping-over is wider than screenwidth - 32.  Which is what happens when I try to set the width == `UIScreen.main.bounds.width`.

The problem was that `screenEdgePadding`'s default are UIEdgeInsets(16).
Adding this fixed my problem:
```
$0.screenEdgePadding = UIEdgeInsets(top: 16, left: 0, bottom: 16, right: 0)
```
When I do this I don't need to explicitly set the width.

The code that uses this is `func calculateFrame()` in `Popover`.

**Comment by aheze** [comment]
Awesome, glad it worked!

**Comment by DavidSReich** [comment]
Thanks for the useful library.

The design of the project I'm working on wants messages to overlap the navigation title.  That's easy to do on the first screen with the NavigationView.  But not easy on successive screens reached via NavigationLink because the nav bar is owned by a previous screen.  Popover solves that easily.
They also want things like menus to sit at the bottom and cover a tab bar with an overlay of a transparent background on top of the rest of the screen (include the title).
All of that architecture is not readily accessible (or coverable) from a View that is deeply nested.  Again, Popover solves that one.
