### ISSUE TITLE
Mac catalyst mode does not seem to be supported, and the following code fails in scrolling of Scrollview running on mac

### ISSUE THREAD

**Issue by wisepmlin** [aheze/Popovers#9]
```swift
GeometryReader {
    proxySubType in
    ItemSelectorView(title: selecedsubtype == -1 ? "选择子类" : products.projectsubtype,
                     animating: $showSubTypePicker,
                     isSeleced: $selecedsubtype)
        .onTapGesture {
            hideKeyboard()
            if products.projecttype.isEmpty {
                self.present = true
                msgBody = "请先选择-品类"
                return
            }
            if !products.projecttype.isEmpty {
                self.showSubTypePicker = true
            }
        }
        .popover(present: $showSubTypePicker,
                 attributes: {
            $0.rubberBandingMode = .none
        }) {
            SK_Picker(selection: $products.projectsubtype,
                      selectionNum: $selecedsubtype,
                      showPicker: $showSubTypePicker,
                      array: products.projecttype == "游戏" ? palyTagOptions : applyTagOptions,
                      title: "选择子类型")
                .padding(CGFloat.bl_4)
                .frame(width: proxySubType.size.width, height: proxySubType.size.width)
                .background(.bar)
                .cornerRadius(CGFloat.bl_4.double)
                .shadow(color: Color.black_c.opacity(0.5), radius: 8, x: 0, y: 2)
                .padding(.vertical, CGFloat.bl_4.half)
        }
}
```

**Comment by aheze** [comment]
@wisepmlin do you get an error? Or is the performance just really bad

**Comment by wisepmlin** [comment]
When I used maccatalyst to use the software, I found that scrolling views nested with Popovers were not available

**Comment by aheze** [comment]
Interesting. I’ve never used Mac Catalyst before, will experiment. In the meantime, try updating to Popovers v1.1.0. It no longer overlays a uiwindow for the popovers.

**Comment by wisepmlin** [comment]
> 有趣。我以前从未使用过Mac Catalyst，我会尝试的。与此同时，尝试更新到弹出窗口v1.1.0。它不再覆盖弹出窗口的ui窗口。

Thumbs up to your ability to act

**Comment by wisepmlin** [comment]
.popover(present: $showTypePicker,
                                             attributes: {
                                                 $0.rubberBandingMode = .none
                                             }) {

                                                 ScrollView {
                                                     ForEach(0...10, id:\.self) { item in
                                                         Text("\(item)")
                                                     }
                                                 }
                                                 .padding(CGFloat.bl_4)
                                                 .frame(width: proxyType.size.width, height: 73)
                                                 .background(.bar)
                                                 .cornerRadius(CGFloat.bl_4.double)
                                                 .shadow(color: Color.black_c.opacity(0.5), radius: 8, x: 0, y: 2)
                                                 .padding(.vertical, CGFloat.bl_4.half)
                                    }
<img width="199" alt="33" src="https://user-images.githubusercontent.com/74945717/148487539-6af0b11e-a378-4dab-a24f-cbbcf311d451.png">

Add ScrollView to Popover, under Maccatalyst, scrolling doesn't work

Works under the iPad

**Comment by wisepmlin** [comment]
<img width="199" alt="33" src="https://user-images.githubusercontent.com/74945717/148487759-b262ee53-2459-47ad-8914-7878b8af0905.png">

**Comment by aheze** [comment]
@wisepmlin sorry for the late response. Did you get it to work after updating to [v1.2.0](https://github.com/aheze/Popovers/releases/tag/1.2.0)?

**Comment by wisepmlin** [comment]
Hello, recently in solving other problems! Only now to get back to you! After testing, the latest version 1.2 has not yet solved the scrollview scrolling problem under maccatalyst

**Comment by aheze** [comment]
Hmm ok... I'm going to be kind of busy this week and probably won't be able to push a fix soon. But if you have any Mac Catalyst experience, feel free to fork the library and make whatever changes you want. Then just raise a PR and I'll merge it.

**Comment by wisepmlin** [comment]
Development process On the issue of adapting mac catalyst, our team has now chosen to deprecate it, and now do not develop the mac catalyst version!

**Comment by aheze** [comment]
Alright. I’m closing this for now since Mac Catalyst doesn’t seem very widespread. If anyone else needs Mac Catalyst support, feel free to fork the repo and make a PR.
